package com.kraken.config.security.exchange.filter.api;

public enum ExchangeFilterMode {
  WEB, // Use the security token sent by the frontend to authenticate requests
  API // Use a token generated by the backend to authenticate requests
}
